In [25]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.naive_bayes import  MultinomialNB, BernoulliNB, ComplementNB
import joblib

In [26]:
str(LinearSVC(), )

'LinearSVC()'

In [27]:
df = pd.read_csv("data/finished_products.csv")

In [28]:
df.category_label = df.category_label.astype("category")

In [29]:
df

                                           product_title category_label
0                        apple iphone 8 plus 64gb silver  mobile_phones
1                    apple iphone 8 plus 64 gb spacegrau  mobile_phones
2      apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...  mobile_phones
3                    apple iphone 8 plus 64gb space grey  mobile_phones
4      apple iphone 8 plus gold 5.5 64gb 4g unlocked ...  mobile_phones
...                                                  ...            ...
30881  smeg fab28 60cm retro style right hand hinge f...        fridges
30882  smeg fab28 60cm retro style left hand hinge fr...        fridges
30883  smeg fab28 60cm retro style left hand hinge fr...        fridges
30884     candy 60cm built under larder fridge cru160nek        fridges
30885           neff k4316x7gb built under larder fridge        fridges

[30886 rows x 2 columns]

In [30]:
X = df[["product_title"]]
y = df["category_label"]

In [31]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y, shuffle=True
)

In [32]:
X_train

                                           product_title
26632                      smeg fc400x2pe fridge freezer
6400                  lg 42lb5610 full hd led television
15376  zanussi zdf22002xa full size dishwasher stainl...
20627  beko wtb820e1w 8 kg 1200 spin washing machine ...
5145   samsung ue55nu7300 55 curved ultra hd certifie...
...                                                  ...
18979                         hoover dxoc510c3/dxoc510c3
13177  panasonic nn st479sbpq family solo auto sensor...
16096       beko dis15010 slimline integrated dishwasher
29022  smeg fab5rrd 40cm red small 50 s style right h...
25534                hoover hdff618w freestanding fridge

[24708 rows x 1 columns]

In [33]:
def train_model(model):
    preprocessor = ColumnTransformer(
        transformers= [
            ("title", TfidfVectorizer(), "product_title"),
        ]
    )

    pipeline = Pipeline([
        ("preprocessing", preprocessor),
        ("classifier", model)
    ])
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    c_report = classification_report(y_test, y_pred, output_dict=True)

    metrics = {
    "model": str(model)[:-2],
    "model_weights" : pipeline,
    "average_score": round(c_report["accuracy"], 3),
    "precision": round(c_report["macro avg"]["precision"], 3),
    "f1-score": round(c_report["macro avg"]["f1-score"], 3),
    "recall": round(c_report["macro avg"]["recall"], 3),
    }
    return metrics

In [12]:
# 'macro avg': {'precision': 0.9740398156374849,
#   'recall': 0.9649694714140735,
#   'f1-score': 0.9693360117701766,
#   'support': 6178.0},

In [34]:
results = []
for i in [RandomForestClassifier(), LinearSVC(), SVC(), MultinomialNB(), BernoulliNB(), ComplementNB()]:
    print(i)
    in_rez= train_model(i)
    print(in_rez)
    results.append(in_rez)

RandomForestClassifier()
{'model': 'RandomForestClassifier', 'model_weights': Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('title', TfidfVectorizer(),
                                                  'product_title')])),
                ('classifier', RandomForestClassifier())]), 'average_score': 0.964, 'precision': 0.972, 'f1-score': 0.965, 'recall': 0.959}
LinearSVC()
{'model': 'LinearSVC', 'model_weights': Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('title', TfidfVectorizer(),
                                                  'product_title')])),
                ('classifier', LinearSVC())]), 'average_score': 0.97, 'precision': 0.978, 'f1-score': 0.971, 'recall': 0.965}
SVC()
{'model': 'SVC', 'model_weights': Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('title', TfidfVectorizer(),
                                                  'product_title')])),
                ('classifier', SVC())]), 'average_score': 0.962, 'precision': 0.978, 'f1-score': 0.965, 'recall': 0.953}
MultinomialNB()
{'model': 'MultinomialNB', 'model_weights': Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('title', TfidfVectorizer(),
                                                  'product_title')])),
                ('classifier', MultinomialNB())]), 'average_score': 0.926, 'precision': 0.971, 'f1-score': 0.895, 'recall': 0.883}
BernoulliNB()
{'model': 'BernoulliNB', 'model_weights': Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('title', TfidfVectorizer(),
                                                  'product_title')])),
                ('classifier', BernoulliNB())]), 'average_score': 0.9, 'precision': 0.965, 'f1-score': 0.872, 'recall': 0.851}
ComplementNB()
{'model': 'ComplementNB', 'model_weights': Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('title', TfidfVectorizer(),
                                                  'product_title')])),
                ('classifier', ComplementNB())]), 'average_score': 0.962, 'precision': 0.979, 'f1-score': 0.954, 'recall': 0.941}

In [14]:
model = max(results, key=lambda d: d["f1-score"])["model_weights"]

In [15]:
model

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('title', TfidfVectorizer(),
                                                  'product_title'),
                                                 ('merchant', MinMaxScaler(),
                                                  ['merchant_id']),
                                                 ('product_family',
                                                  TfidfVectorizer(),
                                                  'product_family'),
                                                 ('start_name',
                                                  TfidfVectorizer(),
                                                  'special_name')])),
                ('classifier', LinearSVC())])

In [35]:
joblib.dump(model, "models/best_model.joblib")

['models/best_model.joblib']

In [36]:
df = pd.read_csv("data/finished_products.csv").head(5)

In [37]:
df

                                       product_title category_label
0                    apple iphone 8 plus 64gb silver  mobile_phones
1                apple iphone 8 plus 64 gb spacegrau  mobile_phones
2  apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...  mobile_phones
3                apple iphone 8 plus 64gb space grey  mobile_phones
4  apple iphone 8 plus gold 5.5 64gb 4g unlocked ...  mobile_phones

In [39]:
X = df[["product_title"]]
y = df["category_label"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y, shuffle=True
)

In [40]:
X_train

                                       product_title
4  apple iphone 8 plus gold 5.5 64gb 4g unlocked ...
2  apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...
1                apple iphone 8 plus 64 gb spacegrau
0                    apple iphone 8 plus 64gb silver

In [41]:
def retrive_model(path = "models/best_model.joblib"):
    return joblib.load(path)

In [42]:
X_test

                         product_title
3  apple iphone 8 plus 64gb space grey

In [43]:
model_pipeline = retrive_model()
model_pipeline.predict(X_test[["product_title"]])

ValueError: columns are missing: {'special_name', 'merchant_id', 'product_family'}